services:
  frontend:
    container_name: onlineeventmanagement_frontend
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: always

  booking-service:
    container_name: onlineeventmanagement_booking-service
    build: ./booking-service
    ports:
      - "${BOOKING_SERVICE_PORT}:8000"
    environment:      
      # PORT
    - PORT=${BOOKING_SERVICE_PORT}

      # POSTGRES CONNECTION
    - DB_USER=${POSTGRES_USER}
    - DB_HOST=${POSTGRES_HOST}
    - DB_NAME=${POSTGRES_DB}
    - DB_PASSWORD=${POSTGRES_PASSWORD}
    - DB_PORT=${POSTGRES_PORT}

      # RABBITMQ CONNECTION
    - RABBITMQ_URL=${RABBITMQ_URL}
    - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}

      # EVENT SERVICE CONNECTION
    - SPRING_BOOT_URL=${SPRING_BOOT_URL}

      # FRONTEND URL
    - FRONTEND_URL=${FRONTEND_URL}

      # JWT SECRET
    - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
    restart: always
  
  user-service:
    container_name: onlineeventmanagement_user-service
    build: ./user-service
    ports:
      - "${USER_SERVICE_PORT}:8000"
    environment:
      # JWT CONFIGURATION
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

      # DATABASE URL [POSTGRES]
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

      # FRONTEND URL
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - mongo
    restart: always
    
  event-service:
    container_name: onlineeventmanagement_event-service
    build: ./event-service
    ports:
      - "${SPRING_BOOT_PORT}:8080"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo
    restart: always
    
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    restart: always
