apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service-deployment
  namespace: onlineeventbookingmuhammadahmad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      namespace: onlineeventbookingmuhammadahmad
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: 22i1056/cs4067-assgt-eventbooking-22i-1056-muhammadahmad-repo-event-service:latest
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: onlineeventbookingmuhammadahmad-secret
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: onlineeventbookingmuhammadahmad-secret
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  key: MONGO_HOST
                  name: onlineeventbookingmuhammadahmad-config
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  key: MONGO_PORT
                  name: onlineeventbookingmuhammadahmad-config
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  key: MONGO_DB
                  name: onlineeventbookingmuhammadahmad-config

            - name: SPRING_MONGODB_URI
              value: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@$(MONGO_HOST):$(MONGO_PORT)/$(MONGO_DB)?authSource=admin"
          ports:
            - containerPort: 8080
          
---

apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: onlineeventbookingmuhammadahmad
spec:
  selector:
    app: event-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP