apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: onlineeventbookingmuhammadahmad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      namespace: onlineeventbookingmuhammadahmad
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: 22i1056/cs4067-assgt-eventbooking-22i-1056-muhammadahmad-repo-booking-service:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 3001
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: onlineeventbookingmuhammadahmad-secret 
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: onlineeventbookingmuhammadahmad-secret
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: onlineeventbookingmuhammadahmad-config
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: onlineeventbookingmuhammadahmad-config            
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: onlineeventbookingmuhammadahmad-config
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_URL
                  name: onlineeventbookingmuhammadahmad-config
            - name: RABBITMQ_QUEUE
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_QUEUE
                  name: onlineeventbookingmuhammadahmad-config
            - name: SPRING_BOOT_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_BOOT_URL
                  name: onlineeventbookingmuhammadahmad-config
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  key: FRONTEND_URL
                  name: onlineeventbookingmuhammadahmad-config
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: onlineeventbookingmuhammadahmad-secret

---

apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: onlineeventbookingmuhammadahmad
spec:
  selector:
    app: booking-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30003