apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  namespace: onlineeventbookingmuhammadahmad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      namespace: onlineeventbookingmuhammadahmad
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  key: MONGO_HOST
                  name: onlineeventbookingmuhammadahmad-config
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGO_EXPRESS_USERNAME
                  name: onlineeventbookingmuhammadahmad-secret
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_EXPRESS_PASSWORD
                  name: onlineeventbookingmuhammadahmad-secret
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: onlineeventbookingmuhammadahmad-secret
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: onlineeventbookingmuhammadahmad-secret
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: onlineeventbookingmuhammadahmad
spec:
  selector:
    app: mongo-express
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081